charmbracelet/x

- exp/ordered/go.mod
I know `min`/`max` will be polymorphic in a forthcoming Go … but until then this fixes the implementation here.
> fix(ordered): module name

- README.md
- exp/slice/go.mod
- exp/slice/slice.go
- exp/slice/slice_test.go
- go.work
`Take` returns a sub-slice containing at most _N_ items from the head of a slice. I know Go’s not tail-call optimized, but I can still see this being handy.
> feat: generic slice 'take' function

- exp/ordered/go.mod
- exp/ordered/go.sum
- exp/ordered/ordered.go
- exp/ordered/ordered_test.go
I have written hundreds of `firstNonEmpty` functions over the years, guess this is a good place for it.
Also using stdlib `cmp` instead of `/x/exp/constraints`.
And 100% test coverage :)
> feat: add ordered.First, tests, use stdlib cmp

- README.md
- exp/strings/go.mod
- exp/strings/join.go
- exp/strings/join_test.go
- go.work
At last, join strings in the way they would be read. For example, `[]string{"cheese", "beans", "jalapeños"}` can become `"cheese, beans, and jalapeños"`, with a flick of the wrist.
```go
import str "gitub.com/charmbracelet/x/exp/strings"
x := []string{"eins", "zwei", "drei"}
s := str.SpokenLanguageJoin(x, str.DE)
fmt.Println(s) // eins, zwei und drei
```
English users can also opt into to the Oxford Comma with the hot `EnglishJoin` function:
```go
x := []string{"meow", "purr", "raow"}
s := str.EnglishJoin(x, true)
fmt.Println(s) // meow, purr, and raow
```
The following languages are supported:
* German (DE)
* Danish (DK)
* English (EN)
* Spanish (ES)
* French (FR)
* Italian (IT)
* Norwegian ([NO](https://www.bram.us/2022/01/11/yaml-the-norway-problem/))
* Portuguese (PT)
* Swedish (SE)
> feat: join strings with a conjunction in a handful of languages

- go.work
- go.work.sum
- term/conpty/conpty_windows.go
- term/conpty/doc.go
- term/conpty/exec_windows.go
- term/go.mod
- term/go.sum
Add support for windows conpty https://learn.microsoft.com/en-us/windows/console/creating-a-pseudoconsole-session
> feat(term): add term/conpty

- term/term.go
- term/term_other.go
- term/term_test.go
- term/term_unix.go
- term/term_unix_bsd.go
- term/term_unix_other.go
- term/term_windows.go
- term/util.go
This basically ports https://github.com/golang/term but without the VT terminal stuff, ANSI codes, and exports platform-specific terminal state. On Unix, the state is `unix.Termios`, and on Windows, it's a `uint32` representing the console mode
https://learn.microsoft.com/en-us/windows/console/getconsolemode.
> feat(term): add cross-platform console state-aware support

- exp/teatest/send_test.go
- exp/teatest/teatest.go
- exp/teatest/testdata/TestAppSendToOtherProgram.golden
- this documents how to test programs that talk to each other (by adding a test that tests it)
- it also changes the interrupt signal handle to kill instead of quit, which is more appropriate I think
- it also adds `WithANSICompressor` to the default teatest options, as it seems to improve reliability 
refs #37
> teatest: use one program within another, signal handler, ansi compressor

- exp/term/ansi/truncate.go
- exp/term/ansi/truncate_test.go
- exp/term/examples/truncate/main.go
This implements an ANSI and wide-characters aware truncation algorithm that uses the newly merged [ANSI parser state machine][statemachine] and the fantastic library [uniseg](https://github.com/rivo/uniseg).
Since this is using the ANSI state machine, it's compatible with `CSI m`
(SGR) style sequence, `OSC 8` (hyperlinks), and basically any other
escape sequence supported in the state machine (DCS, ESC, SOS, PM, APC).
Related: https://github.com/muesli/reflow/pull/71
[statemachine]: https://github.com/charmbracelet/x/blob/main/exp/term/ansi/parser/transition_table.go
Benchmarks against [`reflow truncate.String`](https://github.com/muesli/reflow/tree/master/truncate):
```
goos: darwin
goarch: amd64
pkg: github.com/charmbracelet/x/exp/term/ansi
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz …
```
> feat(term): ansi: implement ANSI aware truncation

- exp/term/ansi/wrap.go
- exp/term/ansi/wrap_test.go
This is based on @muesli's awesome
[reflow](https://github.com/muesli/reflow) library. It uses the ANSI parser state machine to find escape codes and runes. Since it uses the ANSI parser state machine, it supports OSC, DCS, and other sequences.
Related: https://github.com/muesli/reflow/pull/71
Benchmarks running against reflow:
```
› go test -bench=. -benchmem -run=^$ ./ansi/...
goos: darwin
goarch: amd64
pkg: github.com/charmbracelet/x/exp/term/ansi
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
BenchmarkWrap-16                19056892                66.83 ns/op          111 B/op          1 allocs/op
BenchmarkReflowWrap-16           9982068               122.7 ns/op           164 B/op          4 allocs/op
BenchmarkWordwrap-16             7652895               161.3 ns/op           287 …
```
> feat(term): ansi: implement wrap and wordwrap

- exp/term/ansi/wrap.go
- exp/term/ansi/wrap_test.go
ANSI aware text wrapping that breaks word boundaries only when necessary.
Fixes: https://github.com/charmbracelet/lipgloss/pull/275
Fixes: https://github.com/muesli/reflow/issues/43
> feat(term): ansi: move Wrap to Hardwrap and introduce Wrap

- exp/term/ansi/wrap.go
- exp/term/ansi/wrap_test.go
Properly count escape codes, better handling of breakpoints, and only break word/breakpoint when necessary.
Fixes: https://github.com/charmbracelet/x/issues/58
> fix(term): ansi: account for some wrap edge cases

- exp/teatest/teatest.go
During testing, I need a mechanism to access the `TestModel`'s underlying `program` in order to assign it to a `program` struct that I'm using to send messages back to the TUI during business-logic portions of my app.
In other words, I don't want my test code to have to call `tm.Send`, I'd rather have the existing `Send` calls in my business logic work with the same `program` that the tests are using
Quick and dirty solution is to add a getter for the `program`, but I'm happy to look into other methods.
> feat: adds getter for program field in TestModel

- exp/golden/golden.go
- exp/teatest/go.mod
- exp/teatest/go.sum
- exp/teatest/teatest.go
This adds a new `RequireEqualEscape` function that escapes the golden and model outputs to display ansi sequences
> feat(golden): escapse sequences

- ansi/slice.go
- ansi/slice_test.go
- go.work.sum
Based on the truncate function.
Specify a start point (inclusive) and end point (exclusive) in cell-width units, and get a string back at that exact size.
Handles ansi-codes and multi-length characters.
> feat: Ansi slice function

- ansi/truncate.go
- ansi/truncate_test.go
- ansi/width.go
```
goos: darwin
goarch: arm64
pkg: github.com/charmbracelet/x/ansi
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
TruncateString-16   24.96n ± 1%   25.83n ± 2%  +3.49% (p=0.001 n=10)
│  old.txt   │            new.txt             │
│    B/op    │    B/op     vs base            │
TruncateString-16   65.00 ± 0%   65.00 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
│  old.txt   │            new.txt             │
│ allocs/op  │ allocs/op   vs base            │
TruncateString-16   1.000 ± 0%   1.000 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
```
Fixes: https://github.com/charmbracelet/lipgloss/issues/324
Fixes: https://github.com/charmbracelet/x/pull/106
CC/ @mikelorant @jbcpollak
> fix(ansi): truncate: truncate string when input length is equal to output

- ansi/width.go
- ansi/width_test.go
We need to reset the grapheme state after encountering a non-printable character or when we're not using uniseg for string width (ASCII printables have a width of 1 cell).
Fixes: https://github.com/charmbracelet/x/issues/122
Fixes: https://github.com/charmbracelet/x/issues/123
Fixes: https://github.com/charmbracelet/lipgloss/discussions/332
> fix(ansi): reset uniseq grapheme state after

- ansi/parser.go
- ansi/parser/transition_table.go
- ansi/parser_test.go
- ansi/truncate.go
- ansi/width.go
- ansi/wrap.go
```
goos: darwin
goarch: arm64
pkg: github.com/charmbracelet/x/ansi
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
Parser/simple-16                        80.91µ ± 1%   80.02µ ± 1%   -1.10% (p=0.035 n=10)
Parser/params-16                        83.31µ ± 0%   82.57µ ± 1%   -0.88% (p=0.035 n=10)
Parser/params_and_data-16               82.45µ ± 0%   83.67µ ± 0%   +1.48% (p=0.000 n=10)
ParserUTF8/simple-16                    77.71µ ± 0%   71.73µ ± 0%   -7.69% (p=0.000 n=10)
ParserUTF8/params-16                    76.61µ ± 0%   71.84µ ± 0%   -6.23% (p=0.000 n=10)
ParserUTF8/params_and_data-16           76.46µ ± 0%   71.68µ ± 0%   -6.26% (p=0.000 n=10)
ParserStateChanges/simple-16            207.5n ± 1%   198.3n ± 0%   -4.41% (p=0.000 …
```
> Improve ansi.Parser performance and memory allocs

- ansi/parser.go
- ansi/parser/transition_table.go
- ansi/parser_decode.go
- ansi/parser_decode_test.go
- examples/go.mod
- examples/go.sum
- examples/parserlog/main.go
- examples/parserlog2/main.go
- go.work
This new `ansi.DecodeSequence` replaces the existing ANSI parser by providing a simpler, static method of decoding a single sequence. Instead of passing a `ansi.ParserDispatcher` func, use `ansi.DecodeSequence` to segment the given input into sequences without allocating any memory. This also adds support to sequence widths by using the uniseg library to decode graphemes and report sequence widths instead of manually using uniseg in the dispatcher func in the parser.
See [parserlog2/main.go](https://github.com/charmbracelet/x/blob/ansi/decode-seq/examples/parserlog2/main.go) for an example of how this works compared to [parserlog/main.go](https://github.com/charmbracelet/x/blob/ansi/decode-seq/examples/parserlog/main.go)
some benchmarks:
```
goos: darwin
goarch: arm64
pkg: …
```
> Introduce ansi.DecodeSequence

- ansi/cursor.go
This adds `CSI Ps SP q` (DECSCUSR) and `OSC 22` sequences to change the terminal cursor shape, and the mouse pointer in shape.
> feat(ansi): add cursor and mouse pointer shape sequences

- ansi/mode.go
- ansi/parser_decode.go
This adds the necessary sequences to enable/disable/request mode 2027 (grapheme clustering).
See https://mitchellh.com/writing/grapheme-clusters-in-terminals See https://github.com/contour-terminal/terminal-unicode-core
> feat(ansi): add mode 2027

- ansi/style.go
- ansi/style_test.go
```
goos: darwin
goarch: arm64
pkg: github.com/charmbracelet/x/ansi
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
Style-16   190.4n ± 1%   189.1n ± 3%  -0.71% (p=0.030 n=10)
│  old.txt   │            new.txt             │
│    B/op    │    B/op     vs base            │
Style-16   168.0 ± 0%   168.0 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
│  old.txt   │            new.txt             │
│ allocs/op  │ allocs/op   vs base            │
Style-16   9.000 ± 0%   9.000 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
```
> feat(ansi): add more style attributes

- editor/editor.go
- renamed function from `Cmd` to `Command` to be more similar to the `exec`'s API
- added a `CommandContext` that accepts a context as well, also like `exec`'s API 
- deprecated old `Cmd` function
> feat(editor): allow to pass a context

- ansi/cursor.go
currently, updating to v0.4.0 is a breaking change... so it'll break any bubbletea app on latest bubbletea version.
I think we can roll this for a while and then remove these deprecated options... wdyt?
> fix: compat layer for ansi 0.3->0.4 migration

- ansi/cursor.go
Reverts charmbracelet/x#229
DECSCUSR _has_ an intermediate space character `CSI Ps SP q` where `Ps` is a cursor style integer
> revert: "fix: set cursor style sequence"

- ansi/wrap.go
- ansi/wrap_test.go
Tabs should be treated as zero-width characters when wrapping text.
Fixes: https://github.com/charmbracelet/x/issues/237
> fix(ansi): tab is a zero-width character

- exp/golden/golden.go
This change makes `RequireEqual` always escape the control codes and escape sequences from the diff output when comparing the golden file with the output.
It also deprecates the `RequireEqualEscape` function, which was previously used to escape the control codes and escape sequences from the output before comparing it with the golden file.
> fix(golden): always show escaped golden files when comparing the outputs

- ansi/modes.go
A map that represents the terminal modes that can be set or reset. By default, all modes are ModeNotRecognized.
> feat(ansi): implement ansi.Modes type

- ansi/truncate.go
- ansi/truncate_test.go
- go.work.sum
Truncate returns the first N chars of the string.
TruncateLeft skips the first N chars of the string, returning the rest.
pretty sure it can be improved.
will be useful for implementing an horizontal scroll in viewport, e.g. https://github.com/charmbracelet/bubbles/pull/240
> feat(ansi): TruncateLeft

- ansi/truncate.go
- ansi/truncate_test.go
I feel like this will be useful in more places.
Extracted from https://github.com/charmbracelet/gum/pull/789
> feat(ansi): cut

- ansi/truncate.go
- ansi/truncate_test.go
I added a couple more test cases here as I was curious to see how `Cut` behaves.
One minor question: if the size of the cut is zero, should we just return the empty string? This is how it currently works:
```go
Cut(\x1b[7mHello\x1b[m", 2, 2) == "\x1b[7m\x1b[m" // true
```
Update: after seeing https://github.com/charmbracelet/lipgloss/pull/458 I would suggest we do but the extra check in to not render unnecessary ANSI.
> Add a few more test cases

- ansi/winop.go
This implements the XTWINOPS and WindowOp functions that allow manipulating the terminal window. Using `ansi.WindowOp` with `ReportWindowSizeWinOp`, we can query the terminal for the pixel size of the window. This is useful for rendering images in the terminal and calculate the cell size based on how many pixels and cells are available.
See https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Functions-using-CSI-_-ordered-by-the-final-character-lparen-s-rparen:CSI-Ps;Ps;Ps-t.1EB0
> feat(ansi): XTWINOPS and WindowOp functions

- ansi/iterm2.go
- ansi/iterm2/file.go
- ansi/iterm2/file_test.go
- ansi/iterm2_test.go
This implements the iTerm2 Inline Image Protocol. The protocol allows applications to display images inline in the terminal. The protocol is documented at https://iterm2.com/documentation-images.html.
> feat(ansi): iterm2: add iTerm2 Inline Image Protocol

- ansi/truncate.go
- ansi/truncate_test.go
Changes:
- Fixed `truncateLeft` description based on @caarlos0 's [PR](https://github.com/charmbracelet/x/pull/301)
- Fixed edge case: Return string if we're truncating 0 chars from the left (see test case) 
Issue: #329
> fix(ansi): update truncateLeft description, fix edge case

- input/key_test.go
- input/kitty.go
- input/parse.go
This adds support for parsing Kitty Graphics Protocol responses. This is useful for applications that want to use the Kitty terminal's graphics protocol to render images and other graphics.
When using the protocol, the terminal responds on querying and/or transmitting images. This parses these responses and emits events for them.
> feat(input): support kitty graphics responses

- input/input.go
- input/key_test.go
- input/parse.go
This adds support to parse the xterm window text area size report. This is useful to get the terminal size in pixels and to calculate the cell size.
> feat(input): support parsing xterm window text area size report

- input/kitty.go
This fixes an issue when both shift and caps-lock are on at the same time. In this case, the key should be treated as uppercase as if one of the two was pressed.
> fix(input): kitty: handle ModShift|ModCapsLock as uppercase

- ansi/mouse.go
- ansi/mouse_test.go
This method shouldn't be visible to users using the button consts. For example, Bubble Tea v2 and the new input package use these consts as aliases, and we shouldn't expose this method to them.
> refactor(ansi): mouse: don't export Button method

- vt/csi_screen.go
- vt/terminal_test.go
The changes introduced in this PR are:
1. In `vt/csi_screen.go`, the `ED (Erase in Display)` command `case 0` implementation has been updated to handle erasing from the cursor position more precisely.
The key changes are:
- Now properly handles erasing from the cursor position by splitting into two rectangles
- First rectangle erases from cursor to end of current line
- Second rectangle erases all lines below current line
2. In `vt/terminal_test.go`, all test cases have been updated to use `\x1b[2J` (clear entire screen) instead of `\x1b[0J` (clear from cursor down) for initialization. 
3. `ED` command test cases have also been updated to reflect the updated implementation. 
Ref: [Wikipedia CSI codes](https://en.wikipedia.org/wiki/ANSI_escape_code#Control_Sequence_Introducer_commands), …
> Fix handling for `ED (Erase in Display)` control sequence

- ansi/method.go
- ansi/parser_decode.go
- ansi/truncate.go
- ansi/width.go
- ansi/width_test.go
- ansi/wrap.go
This commit introduces a new type, Method, that represents how the renderer should calculate the display width of cells. It adds helper methods to the Method type that allow users to use either WcWidth, which uses go-runewidth, or GraphemeWidth, which uses uniseg, to calculate the width of strings and text.
Methods like `ansi.StringWidth`, `ansi.Truncate`, `ansi.TruncateLeft`, and `ansi.Cut` now have variants that are aware of wide characters and runes. These new methods are suffixed with `Wc` and use go-runewidth to calculate the width of strings.
Related: https://github.com/charmbracelet/x/pull/217
> feat(ansi): define Method and make wcwidth aware variants

- editor/editor.go
Personal preference, but I find that with `int` as the default numeric unit in Go I'm always a little thrown off when converting to a `uint` for high level cases like this.
> chore(editor): use ints instead of uints to avoid conversions

- input/driver_windows.go
Handle cancelio in handleConInput on Windows. This fixes a bug where canceling the input reader would cause the program to return an unexpected error instead of ErrCanceled.
> fix(input): windows: handle cancelio in handleConInput

- ansi/finalterm.go
This adds the FinalTerm shell integration sequences. These are used for shell integrations and are used to mark the start and end of the shell prompt, command execution, and command output.
See https://iterm2.com/documentation-shell-integration.html for more information.
Related: https://github.com/charmbracelet/sequin/issues/46
> feat(ansi): add FinalTerm shell integration sequences

- input/cancelreader_other.go
- input/cancelreader_windows.go
- input/driver.go
- input/parse.go
We need to enable mouse mode on Windows on demand. This is done by adding a new flag to the input driver and passing it to the cancelreader to enable mouse mode.
Related: https://github.com/charmbracelet/bubbletea/issues/1313
> fix(input): windows: mouse mode flag

- cellbuf/wrap.go
- cellbuf/wrap_test.go
This uses the same algorithm as in `ansi.Wrap` except that it also keeps
track of the cursor style and link state and applies them to the wrapped
text.
We should use this instead of `ansi.Wrap` wherever styles and Hyperlinks
are important.
> feat(cellbuf): implement style aware text wrapping

- cellbuf/cell.go
- cellbuf/wrap.go
- cellbuf/wrap_test.go
This will treat formatted styled spaces as word characters. We need this because for example a space with a background shouldn't be truncated by the wrap.
> fix(cellbuf): wrap: properly handle formatted spaces

- ansi/color.go
- ansi/color_test.go
This adds support for converting colors to 16 and 256 colors in the ANSI color space. The conversion functions `Convert16` and `Convert256` allow for easy mapping of colors to the respective ANSI color spaces.
> feat(ansi): support color conversion to 16 and 256 colors

- exp/slice/slice.go
- exp/slice/slice_test.go
Just a small convenience function to have clearer code.
```go
last := obj.List[len(obj.List)-1]
```
Becomes:
```go
last := slice.Last(obj.List)
```
> feat(exp/slice): add `slice.Last` helper func

- cellbuf/pen.go
- cellbuf/wrap.go
This adds a generic writer that keeps track of style and link state for the purpose of wrapping output with new lines. This is a replacement for the reflow/ansi package.
> feat(cellbuf): add a generic writer that keeps track of style state

- examples/go.mod
- examples/go.sum
- examples/toner/main.go
- exp/toner/go.mod
- exp/toner/go.sum
- exp/toner/toner.go
This is a small package that provides a way to colorize escape sequences from strings and byte slices using charm tones.
```go
ansiSequences := "\033[31mHello, World!\033[0m"
colored := toner.Strings(ansiSequences)
fmt.Println(colored) // Outputs colorizes the sequences using charm tones.
```
> feat(toner): add initial implementation

- examples/charmtone/main.go
- exp/charmtone/charmtone.go
- exp/color/blend.go
- exp/color/go.mod
- exp/color/go.sum
- go.work
This moves Charmtone's color blend function to its own package and generalizes it so it can work with any `color.Color`. We're still maintaining `charmtone.Blend` for convenience, however.
> feat: move gradient generator to its own package

- exp/teatest/teatest.go
- exp/teatest/v2/teatest.go
I am running into a race condition where the final model would still be nil rather than the expected model even after the program completed the the done signal sent. This seems to fix it.
Send the final model ‘_before_’ sending the program is done signal, such that `FinalModel()` can correctly receive the final model from `modelCh` rather than returning the default `tm.model` which is null.
```go
func (tm *TestModel) FinalModel(tb testing.TB, opts ...FinalOpt) tea.Model {
tm.waitDone(tb, opts)
select {
case m := <-tm.modelCh:
tm.model = m
return tm.model
default:
return tm.model
}
}
```
Specifically, in the above code `tm.waitDone(tb, opts)` would wait for `doneCh` to receive true _before_ selecting on the `tm.modelCh` which might not receive the final model since it is being sent …
> teatest: fix race condition
